In [1]:
from tabula import read_pdf
import numpy as np

In [79]:
fd = read_pdf("HI_assay/WIC-VCM-NH202425.pdf", pages="all")

In [80]:
#parse pdf .....
import fnmatch
def func(l, s):
    return [i for i in l if re.search(s, i)]
ll = []
cnt = 0
for i in range(len(fd)):
    ff = fd[i].columns.tolist()
    c = len(func(ff,'Haemagglutination'))
    if c == 1:
        ll.append(cnt)
    else:
        pass
    cnt +=1

In [81]:
#fd[3].iloc[:,3].str.split(' ', expand=True)

fd[ll[1]]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Haemagglutination inhibition titre
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Post-infection ferret antiserum
1,NaN,Viruses Other,NaN,NaN,NaN,NaN,NaN,IVR-215,A/Sydney A/Sydney A/Victoria/ IVR-238 A/Wiscon...
2,NaN,information,NaN,NaN,NaN,NaN,NaN,A/Vic/2570/19,5/21 5/21 4897/2022A/Vic/4897/22 67/2022
3,NaN,NaN,NaN,NaN,NaN,NaN,Passage,Egg,MDCK Egg MDCK Egg MDCK
4,NaN,NaN,NaN,NaN,NaN,NaN,Ferret F17/23number,F37/21,F46/22 F04/22 F05/23 F07/23
5,NaN,COPY AND PASTE VALUES!!,NaN,Genetic group,Collection Date,NaN,Genetic group,5a.2(C),5a.2a(C.1) 5a.2a(C.1) (C.1.1.1) 5a.2a.1 (C.1.1...
6,NaN,REFERENCE VIRUSES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,"IVR-215 (A/Victoria/2570/2019) K130N, N156K, L...",NaN,5a.2 (C),2018-11-22,NaN,E4/D7/E3,1280,640 640 640 1280 640
8,NaN,"A/Sydney/5/2021 K54Q, A186T, E224A, R259K, K30...",NaN,5a.2a (C.1),2021-10-16DCK3/MDCK4,NaN,NaN,2560,1280 2560 1280 2560 1280
9,NaN,"A/Sydney/5/2021 K54Q, A186T, E224A, R259K, K30...",NaN,5a.2a (C.1),2022-10-31,NaN,E3/E3,1280,640 640 640 1280 640
10,NaN,"A/Victoria/4897/2022 P137S, K142R, T216A, D260...",NaN,5a.2a.1 (C.1.1.1),2022-10-02SIAT2/MDCK2,NaN,NaN,1280,640 640 1280 640 1280
11,NaN,"IVR-238 (A/Victoria/4897/2022) P137S, K142R, T...",NaN,5a.2a.1 (C.1.1.1),2022-10-02,NaN,E3/D6/E1,1280,1280 1280 1280 2560 640
12,NaN,A/Wisconsin/67/2022,NaN,5a.2a.1 (C.1.1),2022-10-25,NaN,MDCK2,640,640 640 1280 640 1280
13,NaN,TEST VIRUSES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,240055.0,A/Iran/25H10/2023,NaN,5a.2a (C.1),2023-08-07SIAT1/MDCK2,NaN,NaN,1280,1280 1280 1280 1280 640
15,240054.0,A/Iran/18H10/2023,NaN,5a.2a (C.1),2023-08-08SIAT1/MDCK1,NaN,NaN,1280,1280 1280 1280 1280 640
16,240053.0,A/Iran/1Q11/2023,NaN,5a.2a (C.1),2023-09-29SIAT1/MDCK1,NaN,NaN,1280,1280 1280 1280 1280 640
17,240073.0,A/Salalah/52329150/2023,NaN,5a.2a (C.1),2023-10-03,NaN,MDCK2,2560,1280 1280 1280 1280 640
18,240052.0,A/Iran/16B12/2023,NaN,5a.2a (C.1),2023-10-09,NaN,MDCK,5120,2560 2560 2560 2560 1280

In [183]:
ideal = fd[1].dropna(thresh=6).dropna(axis=1).iloc[:,[0,2,3,4,5,6,7]]
ideal.index = ideal.iloc[:,0]
df_ = ideal.iloc[:,1:]
df_

,5a.2,5a.2a,5a.2a.1,5a.2a.1.1,5a.2a.1.2,5a.2a.1.3
COPY AND PASTE VALUES!!,,,,,,
"IVR-215 (A/Victoria/2570/2019) K130N, N156K, L161I, V250A, E189Q (A195E, Q223R)",1280.0,640.0,640.0,640.0,640.0,320.0
"A/Sydney/5/2021 K54Q, A186T, E224A, R259K, K308R, D94N, T216A",1280.0,1280.0,2560.0,2560.0,1280.0,1280.0
"A/Sydney/5/2021 K54Q, A186T, E224A, R259K, K308R, D94N, T216A (Q223R)",1280.0,640.0,1280.0,1280.0,1280.0,640.0
"A/Victoria/4897/2022 P137S, K142R, T216A, D260E, T277A",2560.0,1280.0,2560.0,2560.0,2560.0,2560.0
"IVR-238 (A/Victoria/4897/2022) P137S, K142R, T216A, D260E, T277A (R142K, Q223R)",640.0,640.0,640.0,640.0,1280.0,320.0
A/Wisconsin/67/2022,1280.0,640.0,1280.0,1280.0,1280.0,1280.0
A/Catalonia/NSVH151105209/2023,2560.0,2560.0,2560.0,2560.0,2560.0,1280.0
A/Catalonia/NSVH132634061/2023,2560.0,2560.0,2560.0,1280.0,1280.0,1280.0
A/Catalonia/NSAV198281926/2023,2560.0,1280.0,1280.0,2560.0,2560.0,2560.0
A/Catalonia/NSVH102162320/2023,1280.0,640.0,1280.0,2560.0,1280.0,1280.0

In [335]:
ncol_ = ideal.shape[1]
nrow_ = ideal.shape[0]
ll = []
index_ = []
for i in range(1,ncol_):
    
    x=np.log2(df_.iloc[:,i-1].to_frame())
    sample_ = x.index.tolist()
    cnt = 1
    for j in range(cnt,ncol_):
        
        x_2 = x.iloc[j-1:,]
        ref = x_2.iloc[0,0]
        candidate = x_2.iloc[1:,0]
        score = ref - candidate.to_numpy()
        ll.extend(score)
        index_sample.append([sample_[j-1],sample_[j]])

        xsample = x_2.index.tolist()
        xref = xsample[0]
        
        for k in range(len(xsample)-1):
            
            xy = xsample[k+1]+"___"+ xsample[0]
            index_.append(xy)

        cnt += 1

In [337]:
len(index_)

234